# Generated by Django 5.2.18 on 2026-10-06 15:16

import django.db.models.deletion
import notas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=44)),
                ('id_doc_fiscal', models.CharField(blank=True, max_length=40)),
                ('modelo', models.CharField(blank=True, max_length=4)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('data_emissao', models.DateTimeField()),
                ('protocolo', models.CharField(blank=True, max_length=60)),
                ('situacao', models.CharField(blank=True, max_length=40)),
                ('emitente_cnpj', models.CharField(blank=True, max_length=20)),
                ('emitente_nome', models.CharField(blank=True, max_length=200)),
                ('emitente_fantasia', models.CharField(blank=True, max_length=200)),
                ('emitente_ie', models.CharField(blank=True, max_length=30)),
                ('emitente_endereco', models.TextField(blank=True)),
                ('emitente_municipio', models.CharField(blank=True, max_length=80)),
                ('emitente_uf', models.CharField(blank=True, max_length=2)),
                ('qtd_itens', models.IntegerField(blank=True, null=True)),
                ('valor_produtos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_tributos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('situacao_credito', models.CharField(blank=True, max_length=80)),
                ('categoria', models.CharField(blank=True, max_length=60)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('url', models.TextField(blank=True)),
                ('html', models.FileField(blank=True, upload_to=notas.models.caminho_html)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ItemNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('codigo', models.CharField(blank=True, max_length=60)),
                ('ean', models.CharField(blank=True, max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('ncm', models.CharField(blank=True, max_length=12)),
                ('cfop', models.CharField(blank=True, max_length=6)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unidade', models.CharField(blank=True, max_length=10)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('valor_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='notas.nota')),
            ],
            options={
                'ordering': ['nota', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('forma', models.CharField(blank=True, max_length=80)),
                ('bandeira', models.CharField(blank=True, max_length=40)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='notas.nota')),
            ],
            options={
                'ordering': ['nota', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoNP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('total_notas', models.IntegerField(blank=True, null=True)),
                ('bilhetes', models.IntegerField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creditos', models.CharField(blank=True, max_length=60)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_np', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['periodo'],
            },
        ),
        migrations.CreateModel(
            name='Placar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.JSONField(default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placar_np', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegraCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padrao', models.CharField(max_length=80)),
                ('categoria', models.CharField(max_length=60)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_categoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['padrao'],
            },
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['usuario', 'data_emissao'], name='notas_nota_usuario_ef04be_idx'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('usuario', 'chave'), name='nota_unica_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='itemnota',
            constraint=models.UniqueConstraint(fields=('nota', 'seq'), name='item_unico_por_nota'),
        ),
        migrations.AddConstraint(
            model_name='pagamentonota',
            constraint=models.UniqueConstraint(fields=('nota', 'seq'), name='pagamento_unico_por_nota'),
        ),
        migrations.AddConstraint(
            model_name='periodonp',
            constraint=models.UniqueConstraint(fields=('usuario', 'periodo'), name='periodo_unico_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='regracategoria',
            constraint=models.UniqueConstraint(fields=('usuario', 'padrao'), name='regra_unica_por_usuario'),
        ),
    ]
