# Generated by Django 5.2.18 on 2026-10-06 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(choices=[('notaparana', 'Nota Paraná'), ('sanepar', 'Sanepar'), ('copel', 'Copel')], max_length=20)),
                ('login_cifrado', models.TextField()),
                ('senha_cifrada', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'servico'), name='credencial_unica')],
            },
        ),
        migrations.CreateModel(
            name='SessaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(choices=[('notaparana', 'Nota Paraná'), ('sanepar', 'Sanepar'), ('copel', 'Copel')], max_length=20)),
                ('estado_cifrado', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('expirada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'servico'), name='sessao_unica')],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(choices=[('notaparana', 'Nota Paraná'), ('sanepar', 'Sanepar'), ('copel', 'Copel')], max_length=20)),
                ('tipo', models.CharField(default='sincronizar', max_length=30)),
                ('origem', models.CharField(default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Na fila'), ('rodando', 'Rodando'), ('ok', 'Concluída'), ('erro', 'Erro'), ('cancelada', 'Cancelada')], default='pendente', max_length=12)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('terminada_em', models.DateTimeField(blank=True, null=True)),
                ('progresso', models.CharField(blank=True, max_length=200)),
                ('mensagem', models.TextField(blank=True)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('log', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
                'indexes': [models.Index(fields=['status', 'criada_em'], name='integracoes_status_162108_idx'), models.Index(fields=['usuario', 'servico'], name='integracoes_usuario_ed59ae_idx')],
            },
        ),
    ]
