# Generated by Django 5.2.18 on 2026-10-06 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faturacopel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas_copel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faturasanepar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas_sanepar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='faturacopel',
            constraint=models.UniqueConstraint(fields=('usuario', 'numero_fatura'), name='copel_fatura_unica'),
        ),
        migrations.AddConstraint(
            model_name='faturasanepar',
            constraint=models.UniqueConstraint(fields=('usuario', 'referencia'), name='sanepar_ref_unica'),
        ),
    ]
