# Generated by Django 5.2.18 on 2026-10-06 15:16

import contas.models
import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('nome', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acessa o admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='cadastrado em')),
                ('pj_habilitado', models.BooleanField(default=False, help_text='Horas, informes e previsão de recebimento PJ. Só aparece para quem tiver isto marcado.', verbose_name='módulo PJ')),
                ('hora_atualizacao', models.TimeField(default=datetime.time(7, 0), verbose_name='atualização automática diária')),
                ('atualizacao_automatica', models.BooleanField(default=True, verbose_name='atualizar sozinho todo dia')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
            managers=[
                ('objects', contas.models.UsuarioManager()),
            ],
        ),
    ]
