# Generated by Django 5.2.18 on 2026-10-06 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('horas', models.FloatField(default=0)),
                ('horas_sobreaviso', models.FloatField(default=0)),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pct_sobreaviso', models.FloatField(default=0.3333333333333333)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_nf', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('previsao', models.BooleanField(default=False, help_text='Mês futuro estimado (ainda sem informe)')),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['mes'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'mes'), name='informe_unico_por_mes')],
            },
        ),
    ]
