# Generated by Django 5.2.18 on 2026-10-06 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lancamento_id', models.BigIntegerField(db_index=True)),
                ('quando', models.DateTimeField(auto_now_add=True)),
                ('campo', models.CharField(max_length=30)),
                ('antes', models.TextField(blank=True, null=True)),
                ('depois', models.TextField(blank=True, null=True)),
                ('origem', models.CharField(blank=True, max_length=60)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quando', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'nome'), name='banco_unico_por_usuario')],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('movimentacao', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], default='Saída', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['movimentacao', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'nome'), name='categoria_unica_por_usuario')],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('movimentacao', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=10)),
                ('banco', models.CharField(blank=True, max_length=60)),
                ('categoria', models.CharField(max_length=60)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pago', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data', 'id'],
                'indexes': [models.Index(fields=['usuario', 'data'], name='financeiro__usuario_0a0a43_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='lancamento_valor_positivo')],
            },
        ),
    ]
