# Generated by Django 5.2.18 on 2026-10-06 15:16

import consumo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaCopel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fatura', models.CharField(max_length=30)),
                ('referencia', models.CharField(max_length=7)),
                ('situacao', models.CharField(blank=True, max_length=30)),
                ('origem', models.CharField(blank=True, max_length=60)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo_kwh', models.FloatField(blank=True, null=True)),
                ('leitura_anterior', models.FloatField(blank=True, null=True)),
                ('leitura_atual', models.FloatField(blank=True, null=True)),
                ('data_leitura', models.DateField(blank=True, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('bandeira', models.CharField(blank=True, max_length=80)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('pdf', models.FileField(blank=True, upload_to=consumo.models.pdf_copel)),
                ('importado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['referencia', 'numero_fatura'],
            },
        ),
        migrations.CreateModel(
            name='FaturaSanepar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=7)),
                ('matricula', models.CharField(blank=True, max_length=30)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_agua', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_esgoto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_servicos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consumo_m3', models.IntegerField(blank=True, null=True)),
                ('leitura_anterior', models.IntegerField(blank=True, null=True)),
                ('leitura_atual', models.IntegerField(blank=True, null=True)),
                ('data_leitura', models.DateField(blank=True, null=True)),
                ('proxima_leitura', models.DateField(blank=True, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('tributos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('situacao', models.CharField(blank=True, max_length=30)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('pdf', models.FileField(blank=True, upload_to=consumo.models.pdf_sanepar)),
                ('importado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['referencia'],
            },
        ),
    ]
